### ISSUE TITLE
app.config stop working after updating to 0.5.1/2

### ISSUE THREAD

**Issue by andlouro** [divio/aldryn-apphooks-config#65]
After updating to the new version(0.5.1 and also 0.5.2) I'm facing an issue.

When creating a new blog post I can’t select the app.config. When I select one from the dropdown list the page reloads but also removes the value select and I can’t save because I don’t have a app.config selected.

**Comment by yakky** [comment]
@andlouro which django version are you on and which blog application are you using?

**Comment by andlouro** [comment]
@yakky I using Django 1.10.8.4 and for the blog Django cms blog 0.9.7. I noticed that the Django version I'm currently using have some issues. I will update it, try again and let you know if this was the problem.

**Comment by yakky** [comment]
aldryn-apphooks-config dropped compatibility with django 1.10 in 0.5+
You can install version 0.4.2 which is compatible with django 1.10 (or upgrade your django version to 1.11)

**Comment by andlouro** [comment]
Indeed, everything working with django 1.11 and apphooks 0.5.2.
Thanks for your help @yakky !
